# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allusers', '0002_auto_20170603_1525'),
        ('posts', '0002_auto_20170607_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='allusers.AllUser'),
        ),
    ]
