# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllUsers',
            new_name='AllUser',
        ),
    ]
