# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0002_auto_20170531_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
