# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 19:44
from __future__ import unicode_literals

import comment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_auto_20170607_1137'),
        ('allusers', '0002_auto_20170603_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('user', models.ForeignKey(default=1, on_delete=models.SET(comment.models.get_sentinel_user), to='allusers.AllUser')),
            ],
        ),
    ]
