# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 00:49
from __future__ import unicode_literals

import comment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20170607_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(comment.models.get_sentinel_user), to='allusers.AllUser'),
        ),
    ]
