# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
